/****************************************************************************/
/*    FILE:  STANDARD.H                                                     */
/****************************************************************************/

#ifndef _STANDARD_H_
#define _STANDARD_H_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mem.h>
#include <dos.h>
#include <conio.h>

#include "genbor.h"
#include "debug.h"
#include "ticker.h"
#include "memory.h"
#include "file.h"
#include "comm.h"
#include "resource.h"
#include "graphics.h"
#include "mousemod.h"
#include "keyboard.h"
#include "keyscan.h"
#include "ui.h"
#include "uibutton.h"
#include "uitext.h"

#include "packet.h"

/* UI screens: */
#include "dispatch.h"
#include "townsqr.h"
#include "pub.h"
#include "store.h"
#include "mtower.h"

#include "play.h"
#include "view.h"
#include "pics.h"

#endif

/****************************************************************************/
/*    END OF FILE:  STANDARD.H                                              */
/****************************************************************************/
